### ISSUE TITLE
stylelint doesn't lint scss files

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [advanced-astro/astro-prolint#3]
Your config doesn't lint .scss files i did an update that works perfectly
[https://pastebin.com/Mwq3fiz0](https://pastebin.com/Mwq3fiz0)

Thank you for your work

**Comment by redwerkz** [comment]
Thanks for your input :) 
Fixed with https://github.com/advanced-astro/astro-prolint/commit/84088b8e71ee0e7ebc3a9abcead555624366f190
